AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Fargate Service Stack with CodeDeploy Blue-Green Deployment'

Parameters:
  AppName:
    Type: String
    Default: 'java-full-stack'
  VPCId:
    Type: String
  ECSClusterName:
    Type: String
  ALBArn:
    Type: String
  ALBDNSName:
    Type: String
  ALBSecurityGroupId:
    Type: String
  ECSSecurityGroupId:
    Type: String
  PrivateSubnet1Id:
    Type: String
  PrivateSubnet2Id:
    Type: String
  ECRRepositoryURI:
    Type: String
  ECSTaskExecutionRoleArn:
    Type: String
  ECSTaskRoleArn:
    Type: String
  ALBTargetGroupArn:
    Type: String
  CloudWatchLogGroupName:
    Type: String
  ALBTargetGroupName:
    Type: String
    Description: 'ALB Target Group Name from Infrastructure stack'
  ALBListenerArn:
    Type: String
    Description: 'ALB listener Name from Infrastructure stack'
  CodeDeployServiceRoleArnParam:
    Type: String
    Description: 'CodeDeploy Service Role ARN'

Resources:
  # --- ECS TASK DEFINITION ---
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AppName}-Task
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref ECSTaskExecutionRoleArn
      TaskRoleArn: !Ref ECSTaskRoleArn
      ContainerDefinitions:
        - Name: !Sub ${AppName}-Container
          Image: !Sub ${ECRRepositoryURI}:latest
          Essential: true
          PortMappings:
            - ContainerPort: 8080
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogGroupName
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs

  # --- CODE DEPLOY RESOURCES FOR BLUE-GREEN ---
  CodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Sub ${AppName}-CodeDeploy-App
      ComputePlatform: ECS

  GreenTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AppName}-Green-TG
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VPCId
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: '200'

  TestListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALBArn
      Port: 9000
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref GreenTargetGroup

  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApp
      DeploymentGroupName: !Sub ${AppName}-CodeDeploy-DG
      ServiceRoleArn: !ImportValue 'java-full-stack-CodeDeployServiceRoleArn'
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      BlueGreenDeploymentConfiguration:
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
        DeploymentReadyOption:
          WaitTimeInMinutes: 5
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
      ECSServices:
        - ServiceName: !GetAtt ECSService.Name
          ClusterName: !Ref ECSClusterName
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - TargetGroups:
              - Name: !Ref ALBTargetGroupName
              - Name: !GetAtt GreenTargetGroup.TargetGroupName
            ProdTrafficRoute:
              ListenerArns: 
              - !ImportValue 'java-full-stack-ALBListenerArn'
            TestTrafficRoute:
              ListenerArns: 
                - !Ref TestListener

  # --- ECS SERVICE (Managed by CodeDeploy) ---
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${AppName}-Service
      Cluster: !Ref ECSClusterName
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      DeploymentController:
        Type: CODE_DEPLOY
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !Ref PrivateSubnet1Id
            - !Ref PrivateSubnet2Id
          SecurityGroups:
            - !Ref ECSSecurityGroupId

Outputs:
  ServiceURL:
    Description: 'URL to access the application'
    Value: !Sub http://${ALBDNSName}
  ECSServiceName:
    Description: 'ECS Service Name'
    Value: !Ref ECSService
  CodeDeployAppName:
    Description: 'CodeDeploy Application Name'
    Value: !Ref CodeDeployApp