AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Fargate Service Stack with CodeDeploy Blue-Green Deployment - TRIGGERED!'

Parameters:
  AppName:
    Type: String
    Default: 'java-full-stack'

Resources:

  # --- GREEN TARGET GROUP FOR BLUE-GREEN DEPLOYMENT ---
  GreenTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AppName}-Green-TG
      Port: 80
      Protocol: HTTP
      TargetType: ip
      VpcId: !ImportValue 'java-full-stack-VPCId'
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: '200'
        
  # ECS TASK DEFINITION let me see if it will trigger
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AppName}-Task
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !ImportValue 'java-full-stack-ECSTaskExecutionRoleArn'
      TaskRoleArn: !ImportValue 'java-full-stack-ECSTaskRoleArn'
      ContainerDefinitions:
        - Name: !Sub ${AppName}-Container
          Image: !Sub 
            - "${ECRRepoURI}:latest"
            - ECRRepoURI: !ImportValue 'java-full-stack-ECRRepositoryURI'
          Essential: true
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !ImportValue 'java-full-stack-CloudWatchLogGroupName'
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs



  # --- TEST LISTENER FOR BLUE-GREEN DEPLOYMENT ---
  TestListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !ImportValue 'java-full-stack-ALBArn'
      Port: 9000
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref GreenTargetGroup

  # --- ECS SERVICE (with Load Balancer configuration) ---
  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub ${AppName}-Service
      Cluster: !ImportValue 'java-full-stack-ECSClusterName'
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      DeploymentController:
        Type: CODE_DEPLOY
      LoadBalancers:
        - TargetGroupArn: !ImportValue 'java-full-stack-ALBTargetGroupArn'
          ContainerName: !Sub ${AppName}-Container
          ContainerPort: 8080
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets:
            - !ImportValue 'java-full-stack-PrivateSubnet1Id'
            - !ImportValue 'java-full-stack-PrivateSubnet2Id'
          SecurityGroups:
            - !ImportValue 'java-full-stack-ECSSecurityGroupId'

  # --- CODE DEPLOY APPLICATION ---
  CodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Sub ${AppName}-CodeDeploy-App
      ComputePlatform: ECS

  # --- CODE DEPLOY DEPLOYMENT GROUP ---
  CodeDeployDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    DependsOn: ECSService
    Properties:
      ApplicationName: !Ref CodeDeployApp
      DeploymentGroupName: !Sub ${AppName}-CodeDeploy-DG
      ServiceRoleArn: !ImportValue 'java-full-stack-CodeDeployServiceRoleArn'
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      BlueGreenDeploymentConfiguration:
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 5
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
      AutoRollbackConfiguration:
        Enabled: true
        Events:
          - DEPLOYMENT_FAILURE
          - DEPLOYMENT_STOP_ON_ALARM
      ECSServices:
        - ServiceName: !GetAtt ECSService.Name
          ClusterName: !ImportValue 'java-full-stack-ECSClusterName'
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - TargetGroups:
              - Name: !ImportValue 'java-full-stack-ALBTargetGroupName'
              - Name: !GetAtt GreenTargetGroup.TargetGroupName
            ProdTrafficRoute:
              ListenerArns: 
                - !ImportValue 'java-full-stack-ALBListenerArn'
            TestTrafficRoute:
              ListenerArns: 
                - !Ref TestListener

Outputs:
  ServiceURL:
    Description: 'URL to access the application'
    Value: !Sub 
      - "http://${ALBDNSName}"
      - ALBDNSName: !ImportValue 'java-full-stack-ALBDNSName'
  ECSServiceName:
    Description: 'ECS Service Name'
    Value: !Ref ECSService
  CodeDeployAppName:
    Description: 'CodeDeploy Application Name'
    Value: !Ref CodeDeployApp
  TestListenerArn:
    Description: 'Test Listener ARN for Blue-Green Deployment'
    Value: !Ref TestListener
  GreenTargetGroupName:
    Description: 'Green Target Group Name'
    Value: !GetAtt GreenTargetGroup.TargetGroupName